# Fill in your personal API ID, API hash, and session name. The session name can be any name.
api_id: 18031383
api_hash: "ca3e473a2237fdd835cb1f85fc419d6b"
session_name: "ryan_v404"
# api_id: 12622619
# api_hash: "8b71b8c43075941645017b5e163b4971"
# bot_token: "5266680121:AAFNZ-7Md81Og0nFkDZLMg-dosG0NOoY-SE"

# Obtain a channel's ID by forwarding any message from it to @userinfobot and remove the '-100' from the beginning of the ID.
# Do not use quotes for channel ID's.
input_channel_ids:
  - 1218410161
  - 1138914412
  - 1074511071
  - 1451734813
  - 1200595041
  - 1355540894
  - 1464146642
  - 1514685631
  - 1246399946
  - 1012103617
  - 1168636470
  - 1136444638
  - 1248668939
  - 1165131018
  - 1321658383
  - 1394050290
  - 1208211067
  - 1101806611
  - 1108403053
  - 1283016748
  - 1053161069
  - 1490843052
  - 1162074204
  - 1072681815
  - 1070471996
  - 1398249245
  - 1510269826
  - 1263953596
  - 1185457530
  - 1310984791
  - 1301174235
  - 1465354533
  - 1227152968
  - 1740760630
  - 1279747448
  - 1473281847
  - 1595839251
  - 1074354585
  - 1127491908
  - 1210987817
  - 1441564230
  - 1462161273
  - 1647639783
  - 1274627304
  - 1393900742
  - 1160296406
  - 1247508011
  - 1012339614
  - 1101170442
  - 1085671411
  - 1256096706
  - 1171552896
  - 1096463945
  - 1326223284
  - 1109403194
  - 1188582446
  - 1287596810
  - 1692271774
  - 1293233260
  - 1400338245
  - 1120807475
  - 1498939244
  - 1736895964
  - 1397380283
  - 1621401381
  - 1234806023
  - 1127853461
  - 1711854867
  - 1495069163
  - 1677003375
  - 1487098807
  - 1200595041
  - 1128083841
  - 1413275904
  - 1386375324
  - 1747601201
  - 1751710558
  - 1181797148
  - 1645044428
  - 1384825788

my_channel_ids:
  - 1128083841
  - 1283178270
  - 1487098807
  - 1280273449
  - 1200595041
  - 1128083841
  - 1105313000
  - 1198589840
  - 1199360700
  - 1457892982
  - 1253415143
  - 1413275904
  - 1386375324
  - 1747601201
  - 1751710558
  - 1677003375
  - 1495069163
  - 1711854867
  - 1127853461
  - 1234806023
  - 1074354585
  - 1326223284
  - 1181797148
  - 1722167948
  - 1352726486
  - 1310984791

ukraine_channel_ids:
  - 1128083841
  - 1457892982
  - 1296487842
  - 1650943557
  - 1199360700
  - 1277703001
  - 1283178270
  - 1184824094
  - 1687769706
  - 1105313000
  - 1463721328
  - 1633412678
  - 1443905793
  - 1361808774
  - 1535810280
  - 1198589840
  - 1606216869
  - 1242446516
  - 1060797702
  - 1280273449
  - 1648919730
  - 1238911077
  - 1253415143
  - 1352726486
  - 1369521679
  - 1294364863
  - 1359932400
  - 1713747301

output_channel_ids:
  - 1712562312
  - 1556049685
  - 1595141006
  - 1712665624
  - 1501240289
  - 1502581881
  - 1506467706
